Vue app cleanup
qbcore-framework/qb-inventory pull request #257
Opened 2022-03-31 14:08 UTC by Mojito-Fivem

Got rid of the brunt of your bloat, reduced the bundle size by 38% by simply changing some dependencies.

2022-03-31 14:22 UTC, restray requested changes
Just need to remove 3 lines in the `package.json` but you did a really good job! Thanks you so much :)

2022-03-31 14:22 UTC, restray commented on package.json
>          "jsdom": "^19.0.0",
You can delete those lines too (don't need those, I used them for development)

2022-03-31 14:31 UTC, Mojito-Fivem commented
I went through and deleted all instances of the `var` keyword, as of ES6 this is deprecated and let/const should be used in it's place. Also fixed some instances of using (==) instead of (===)

2022-03-31 14:42 UTC, restray commented
> If you're migrating your code to Vue you should at least consider using typescript here.

I don't agree with you at all... VueJs is already complicated for most of the servers owners! And most of the FiveM resources works with JS and not TS! Those are my arguments to "not moving on TS"

2022-03-31 14:44 UTC, restray approved these changes
It seems pretty good!

2022-03-31 15:14 UTC, Mojito-Fivem commented
> > If you're migrating your code to Vue you should at least consider using typescript here.
> 
> I don't agree with you at all... VueJs is already complicated for most of the servers owners! And most of the FiveM resources works with JS and not TS! Those are my arguments to "not moving on TS"

Exactly. If you're already going to put working on this resources out of the hands of 99% of the userbase, why would you not go the extra step and use typescript which gives a much better developer experience for not all that much work, I see you already using jsdocs here (some of them are wrong but this PR doesn't correct them) so why would you not simplify with typescript which will self document these functions

2022-03-31 15:14 UTC, itschip commented on html_app/components/AttachmentMenu.vue
> +                if (data.AttachmentData !== null && data.AttachmentData !== undefined) {
You can simplify this with `!data.AttachmentData`

2022-03-31 15:15 UTC, itschip commented on html_app/components/PlayerInventory.vue
> +            const selectedItem = this.items.filter((item) => item.inventory == inventory && item.slot == slot);
No strict equality here?

2022-03-31 15:24 UTC, itschip reviewed
Something to look into.

2022-03-31 15:35 UTC, Mojito-Fivem commented
I'm not going to do it but I'm saying it should be considered if such a rewrite is being done in the first place.

2022-04-01 10:00 UTC, xenfovn commented
I think there will be a lot of people who need to see the number showing the total weight amount of the inventory for some purpose

2022-04-01 10:04 UTC, Mojito-Fivem commented
> I think there will be a lot of people who need to see the number showing the total weight amount of the inventory for some purpose

Relevant to this PR how?

2022-04-04 04:30 UTC, IdrisDose commented
Code looks good, has it been tested?

2022-04-04 04:38 UTC, FjamZoo commented
![image](https://user-images.githubusercontent.com/34508112/161474787-d757a182-af4b-4082-a75e-1edbb02b5bca.png)

I was getting this error which meant I couldn't open the inventory.

2022-04-04 11:28 UTC, Mojito-Fivem commented
In this state the inventory doesn't work as it is, this PR just serves to cleanup the poor practices in the code.

2022-04-04 11:44 UTC, Mojito-Fivem commented
fixed some occurrences of this pepega data.data usage but there's still issues in here of the css not being bundled by the webpack.

2022-04-04 12:56 UTC, restray approved these changes
The code seems fine, all the comments I did, are just suggestions!

2022-04-04 12:56 UTC, restray commented on html_app/components/PlayerInventory.vue
> +                fetchNui("GiveItem", {
Maybe strict equal over here ?

2022-04-04 12:56 UTC, restray commented on html_app/components/PlayerInventory.vue
> +            let changeAmount
Maybe set the value to 0 ?

2022-04-04 12:56 UTC, restray commented on html_app/index.js
> +    app.config.globalProperties.i18n = data
Maybe add `data || {}` in case of error!

2022-04-04 13:34 UTC, Mojito-Fivem commented on html_app/index.js
> +    app.config.globalProperties.i18n = data
I think that's beyond the scope of this PR.

2022-04-04 13:47 UTC, restray commented on html_app/index.js
> +    app.config.globalProperties.i18n = data
You rewrite that part, that's why I'm asking you, I can make another PR after that ;)

2022-04-04 15:48 UTC, merged