Layout Changes (v0.5)
qbcore-framework/qb-inventory pull request #258
Opened 2022-04-03 09:36 UTC by JZSandbox

Overall Design Changes, still not 100% done

2022-04-03 17:45 UTC, erpofficial approved these changes

2022-04-03 20:38 UTC, Branqueador commented
a print of how is going or whats looking ?

2022-04-04 01:29 UTC, KingRyuShin commented
yeah you got a picture of how it will look with your change ?

2022-04-04 13:27 UTC, restray commented
![image](https://user-images.githubusercontent.com/27992458/161554012-2df005a9-32b8-4514-97ed-8ffb2211d447.png)
Having this weird bug too... Flexbox isn't configure well or tiles are setup with fixed values!

2022-04-04 13:33 UTC, restray requested changes
The update is almost complete, need to patch a few things then it's ready to go :D Thanks for your beautiful job :)

2022-04-04 13:33 UTC, restray commented on html_app/components/ItemSlot.vue
> +        <div :class="'item-slot-label ' + (item ? 'isItem ' : '') + (item.isWeapon ? ' isItem ' : '')" v-if="!item || !item.isWeapon" :title="(item ? item.label : '')">
A better syntax for classes would be:
```vue
:class="['item-slot-label', {'isItem': item}, {'isItem': item.isWeapon}]"
```

`item.isWeapon` will make the application crash! So think to replace it white `item && item.isWeapon`

2022-04-04 13:33 UTC, restray commented on html_app/components/PlayerInventory.vue
> +                            account_circle
Add an indent over here

2022-04-04 13:33 UTC, restray commented on html_app/components/PlayerInventory.vue
> +                   <!-- <span id="player-inv-label">{{ playerInventory.playerName }}</span><br>
You can delete unused code ! Git remembers everything :D

2022-04-04 13:33 UTC, restray commented on html_app/components/PlayerInventory.vue
> +                            account_circle
Another tab over here :)

2022-04-04 13:33 UTC, restray commented on html_app/components/PlayerInventory.vue
> +                    <!--<span id="other-inv-label">{{ openedInventory.label }}</span><br>
Another commented code there !

2022-04-04 13:33 UTC, restray commented on html_app/components/PlayerInventory.vue
> +
Can we drop those blank lines?

2022-04-04 13:33 UTC, restray commented on html_app/components/PlayerInventory.vue
> +
Those too?

2022-04-04 13:33 UTC, restray commented on html_app/index.css
> +    /* flex: 0 0 5vw; */
You can delete it too!

2022-04-04 13:33 UTC, restray commented on html_app/index.css
> +#qbcore-inventory {
Please indent all the lines below correctly (magic tips: VSCode CTRL+Shift+P -> Format file)

2022-04-04 13:33 UTC, restray commented on html_app/index.css
> +	display: -webkit-box;
Specifiying webkit and mozilla support is useless for use, Chromium is the only engine that could run any CSS! So we can delete it (just a suggestion)

2022-04-04 13:33 UTC, restray commented on html_app/index.html
> +  <link href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp" rel="stylesheet">
We can have one link (so one request) for both of them !
`https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp|Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap`

2022-04-04 14:23 UTC, JZSandbox commented on html_app/index.css
> +#qbcore-inventory {
Its coming from the scss, that too doesnt matter

2022-04-04 18:04 UTC, SonofGlensow commented
Can you add money to inventory?

2022-04-05 04:10 UTC, merged