bug exploit fixed
qbcore-framework/qb-inventory pull request #262
Opened 2022-04-04 20:27 UTC by buntyverma69

some people are doing drop items then set amount in inventory 000000.000001 then duplicate items.

2022-04-04 20:45 UTC, BerkieBb commented
This does remove a feature where you can inout 0 as the value to move all items from one slot.to another

2022-04-04 20:52 UTC, buntyverma69 commented
@BerkieBb I don't remove zero values in inventory

2022-04-04 20:56 UTC, BerkieBb commented
So you can still input `0` with that code in the `amount` field?

2022-04-04 21:16 UTC, buntyverma69 commented
> So you can still input `0` with that code in the `amount` field?

yes see these hope understand my point https://youtu.be/ihNYrX8-0Tk

2022-04-04 21:26 UTC, BerkieBb commented
That's great

2022-04-05 16:21 UTC, restray commented
There is actually an easier way with HTML, normally (maybe only on web) you should set a `step=1` and it will only allow entire numbers :D (need to be tried, not sure)

2022-04-05 16:27 UTC, restray requested changes
No need to set an empty placeholder, maybe add a `step="1"` to force it!

2022-04-05 23:42 UTC, milotiro95 commented
I look the youtube video and tried many times exactly the sames ways but I just cannot reproduce the bug the guns are automaticly switch into my inventory. Is it fixed ?

2022-06-30 01:28 UTC, TonybynMp4 approved these changes

2022-12-30 14:21 UTC, Z3rio commented
Old PR, no changed files anymore.

2022-12-30 14:21 UTC, closed without merging