Item Duplication FIX
qbcore-framework/qb-inventory pull request #263
Opened 2022-04-05 14:09 UTC by benlynx

Dupe Fix

2022-04-05 14:13 UTC, BerkieBb commented
Are you able to show a comparison of what this fixes?

2022-04-05 14:15 UTC, benlynx commented
> Are you able to show a comparison of what this fixes?

You can check this 
https://github.com/qbcore-framework/qb-inventory/pull/263/commits/743e3b5b39e55d6d3889c5777f7be30a6f9f64dc

2022-04-05 15:54 UTC, Ruqen commented
Still needs some formatting. Printing values/errors is not a good idea, please fix the prints according to the logs.

2022-04-06 11:08 UTC, restray requested changes
I didn't have the time to test it with a live server but your work is impressive!
Thanks for your time, just need 2 or 3 changes :)

2022-04-06 11:08 UTC, restray commented on server/main.lua
> +						print("DUPE ENGELLENDI - 4")
I love the way you're making your prints lmao! But I do not understand this one at all!

Replace it with a createLog please :)

2022-11-20 05:40 UTC, Txc32 approved these changes

2022-11-26 15:32 UTC, ChickenDipper1 commented
Surely this deserves more attention! I'll try this myself, thank you!

2022-12-30 14:22 UTC, Z3rio commented
Abandoned PR and incorrect usage of PR description / not following template

2022-12-30 14:22 UTC, closed without merging