Add background to item information container to
qbcore-framework/qb-inventory pull request #271
Opened 2022-04-17 12:07 UTC by Asaayu

This pull request edits the CSS formatting of the inventory to add a semi-transparent black background to the item information container, allowing effortless reading of the text when placed against bright backgrounds.
Before and after images have been provided to show the changes in the presentation to the end-user.

**Before and After Images**
**[Before #1](https://i.imgur.com/TBCYU1G.png) -- [After #1](https://i.imgur.com/hS0Wg4j.png)**
**[Before #2](https://i.imgur.com/Tjoj0Rx.png) -- [After #2](https://i.imgur.com/pgPW6wj.png)**

2022-06-30 01:23 UTC, TonybynMp4 approved these changes

2022-07-31 19:03 UTC, ShomyTKD approved these changes
Works perfectly on the newest version of qb-inventory! Content is wrapped around in a box with a transparent background that greatly increases readability.

2022-09-16 16:12 UTC, dexter9006 approved these changes

2023-02-24 20:47 UTC, woerki approved these changes
LGTM

2023-02-24 20:48 UTC, woerki approved these changes

2023-02-28 17:18 UTC, Z3rio requested changes

2023-02-28 17:18 UTC, Z3rio commented on html/css/main.css
> +    float: right;
```suggestion
    float: right;
```
Why is float used? Considering it hasnt needed this previously?

2023-02-28 17:18 UTC, Z3rio commented on html/css/main.css
> +    border: 1px solid rgb(68 68 68 / 40%);
```suggestion
    border: 1px solid rgba(68, 68, 68, 0.4);
```
Using rgba instead of rgb

2023-11-07 15:43 UTC, closed without merging