fix nil value for giveitem
qbcore-framework/qb-inventory pull request #290
Opened 2022-05-31 21:17 UTC by bamablood94

**Describe Pull request**
Fixes Nil Value given in console after using /giveitem command with a missing 3rd arguement.

When you do /giveitem id item amount, if you dont specify the amount of items then you get a nil value error in console/chat. This fixes that

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? YES
- Does your code fit the style guidelines? YES
- Does your PR fit the contribution guidelines? YES

2022-05-31 21:19 UTC, bamablood94 commented
Alright, this sould be a fresh branch with just the one change

2022-06-30 01:18 UTC, TonybynMp4 commented
tbh could've just changed the 
`		if amount > 0 then
`
to
`		if amount and amount > 0 then
`

2022-07-25 01:12 UTC, jnccloud commented
> **Describe Pull request** Fixes Nil Value given in console after using /giveitem command with a missing 3rd arguement.
> 
> When you do /giveitem id item amount, if you dont specify the amount of items then you get a nil value error in console/chat. This fixes that
> 
> **Questions (please complete the following information):**
> 
> * Have you personally loaded this code into an updated qbcore project and checked all it's functionality? YES
> * Does your code fit the style guidelines? YES
> * Does your PR fit the contribution guidelines? YES

This is a much more efficient and user friendly way to do this:

```lua
local amount = tonumber(args[3]) or 1
```

If its nil then just set it to 1 to make it more user friendly. Only 5 extra characters :)

2022-07-25 01:14 UTC, jnccloud requested changes
Can be refactored to be more user friendly with less code.

2022-07-25 01:14 UTC, jnccloud commented on server/main.lua
>  	local amount = tonumber(args[3])
You can undo all of your changes and change this line to do it in 5 characters:
```lua
local amount = tonumber(args[3]) or 1
```

2022-07-25 01:14 UTC, jnccloud commented on server/main.lua
> +					end
Revert _all_ of this

2022-07-25 01:14 UTC, jnccloud commented on server/main.lua
> +			TriggerEvent('QBCore:Notify', source, 'Missing Arguement', 'error')
All of these notifications can be reverted too if you use my method

2022-07-25 01:29 UTC, jnccloud commented
This was actually already fixed in: 

https://github.com/qbcore-framework/qb-inventory/commit/2e042e69e67f5fe91fc8bf094adcdf8a05900e26

This should be closed..

2022-07-27 13:39 UTC, closed without merging