Added AddGloveboxItems Event & added support job.type
qbcore-framework/qb-inventory pull request #372
Opened 2022-11-04 07:15 UTC by r0adra93

Added addGloveboxItems event
Added job.type leo match up to the script.

## Description

Added AddGloveboxItems Event & added support job.type

Now glove box items can be added from jobs
and the job.type is setup to work with leo type of police jobs.

## Checklist

- [X] I have personally loaded this code into an updated qbcore project and checked all of its functionality.
- [X] My code fits the style guidelines.
- [X] My PR fits the contribution guidelines.

2022-11-09 19:38 UTC, i-kulgu approved these changes
Tested it out and works without any issues.

2022-11-10 09:16 UTC, tom-osborne requested changes

2022-11-10 09:16 UTC, tom-osborne commented on server/main.lua
> +				QBCore.Debug(other.label)
Debug left over from testing.

2022-11-10 17:07 UTC, tom-osborne commented on server/main.lua
> +				QBCore.Debug(other.label)
TMI

Thanks though!

2022-11-10 17:33 UTC, r0adra93 commented on server/main.lua
> +				QBCore.Debug(other.label)
Updated!

2022-11-11 10:18 UTC, tom-osborne approved these changes

2022-11-11 10:18 UTC, merged