Secured Trunk and Glovebox
qbcore-framework/qb-inventory pull request #380
Opened 2022-11-12 14:08 UTC by r0adra93

Converted the the trunk and glovebox items events into functions and exports.

## Description

## Checklist

- [ ] I have personally loaded this code into an updated qbcore project and checked all of its functionality.
- [ ] My code fits the style guidelines.
- [ ] My PR fits the contribution guidelines.

2022-11-12 14:14 UTC, tom-osborne requested changes

2022-11-12 14:14 UTC, tom-osborne commented on server/main.lua
> ----@return table items
These are [luadoc](https://keplerproject.github.io/luadoc/manual.html#introduction) comments, please add these back in.

2022-11-12 14:14 UTC, tom-osborne commented on server/main.lua
> -RegisterNetEvent('inventory:server:addTrunkItems', function(plate, items)
If we are removing events, we should leave them in and just remove their functionality, replacing it with a helpful error message displayed in the console.

2022-11-12 14:17 UTC, r0adra93 commented on server/main.lua
> -RegisterNetEvent('inventory:server:addTrunkItems', function(plate, items)
Only qb-police job uses it and I was making the change.

2022-11-12 14:17 UTC, r0adra93 commented on server/main.lua
> -RegisterNetEvent('inventory:server:addTrunkItems', function(plate, items)
oh okay I can do that

2022-11-19 23:04 UTC, charj commented on server/main.lua
> ----@param stashId string The stash id to save the items from
seems a shame to remove perfectly good LDoc annotations

2022-11-20 05:10 UTC, r0adra93 commented on server/main.lua
> ----@param stashId string The stash id to save the items from
Resolved

2022-11-23 12:22 UTC, Irishstevie approved these changes
I run this with qb-policejob: https://github.com/qbcore-framework/qb-policejob/pull/422

Tested storage Pull out cars open all the menus 

Works good

2022-11-23 18:56 UTC, charj commented on server/main.lua
> +	if not ply.state.inv_busy then
By flipping this condition you could bring your whole block of conditions down by one level of indentation
```
if not ply.state.inv_busy then 
    return QBCore.Functions.Notify(src, Lang:t("notify.noaccess"), 'error')
end
...
```

2022-11-23 18:57 UTC, charj commented on server/main.lua
> +		if name and id then
The same concept can be applied to this one also

2022-11-23 20:09 UTC, r0adra93 commented on server/main.lua
> +		if name and id then
You do realize when you comment; you need to approve the code.

2022-12-14 18:42 UTC, Z3rio approved these changes
The inventory seems to be working as normal after these changes.

2022-12-15 10:19 UTC, merged

2023-02-22 09:39 UTC, zwkf commented
This PR being merged has created further issues:
https://github.com/qbcore-framework/qb-inventory/pull/422

2023-02-22 09:46 UTC, r0adra93 commented
> This PR being merged has created further issues: #422

Roll it back...