Added Progressbar to Opening Inventory Event
qbcore-framework/qb-inventory pull request #394
Opened 2022-12-05 19:10 UTC by AnishBplayz

## Description

This is an enhancement PR.

The PR Title Describes about it.

2022-12-05 19:15 UTC, AnishBplayz commented
Lint issue - As there are spaces after TAB it shows merge block, will fix it soon if necessary other wise it should be good to merge

2022-12-08 13:05 UTC, Z3rio requested changes
I dont believe people would actually like this to be honest.
If you really want this to get added, then it should have a config value to turn it on / off.

2022-12-08 13:23 UTC, AnishBplayz commented
> I dont believe people would actually like this to be honest. Considering most people want the inventory to open as fast as possible.
> 
> If you really want this to get added, then it should have a config value to turn it on / off.



Noted... will add a config value to it.

2022-12-08 21:11 UTC, AnishBplayz commented
@Z3rio I have added the Config Value to it, also the lint issue is still about inconsistent indentation `spaces followed by TAB` it should be good to merge now....

2022-12-08 21:15 UTC, Z3rio commented on client/main.lua
> +                	maxammo = Config.MaximumAmmoValues,
```suggestion
					action = "open",
					inventory = inventory,
					slots = Config.MaxInventorySlots,
					other = other,
					maxweight = Config.MaxInventoryWeight,
					Ammo = PlayerAmmo,
					maxammo = Config.MaximumAmmoValues,
```

Resolve linting issue

2022-12-08 21:32 UTC, AnishBplayz commented
lint fixed :)

2022-12-09 18:53 UTC, Z3rio requested changes
Just minor fixes, otherwise it looks fine. I will test this ingame shortly.

2022-12-09 18:53 UTC, Z3rio commented on client/main.lua
> +                QBCore.Functions.Progressbar('open_inventory', 'Opening Inventory...', math.random(350, 750), false, true, { -- Name | Label | Time | useWhileDead | canCancel
```suggestion
            QBCore.Functions.Progressbar('open_inventory', 'Opening Inventory...', math.random(350, 750), false, true, { -- Name | Label | Time | useWhileDead | canCancel
```
Fix linting

2022-12-09 18:53 UTC, Z3rio commented on client/main.lua
> +                end, function() -- Play When Cancel
```suggestion
            end, function() -- Play When Cancel
```
Fix linting

2022-12-09 21:38 UTC, AnishBplayz commented
Done @Z3rio

2022-12-11 21:42 UTC, AnishBplayz commented
@Z3rio The branch is synced and should be good to merge now

2022-12-18 04:32 UTC, SKITTLE6969 commented
This works and has stopped all the item drop bugs!!! Thanks for this man <3

2022-12-18 05:15 UTC, AnishBplayz commented
Good to hear that @SKITTLE6969 Buddy <3

2022-12-18 05:15 UTC, AnishBplayz commented
@Z3rio It should be good to merge, Requesting for Review again!

2022-12-24 13:00 UTC, AnishBplayz reviewed
resolved

2023-12-08 05:45 UTC, closed without merging