Giveitem with player dropdown menu
qbcore-framework/qb-inventory pull request #417
Opened 2023-02-13 12:25 UTC by i-kulgu

## Description

With this PR you can give an item more controlled.
You'll get a list of nearby players and when you choose a player it will give the item to that selected player.

Preview:
https://www.youtube.com/watch?v=WtpmP7GfGF0

## Checklist

- [X ] I have personally loaded this code into an updated qbcore project and checked all of its functionality.
- [X ] My code fits the style guidelines.
- [X ] My PR fits the contribution guidelines.

2023-02-14 03:43 UTC, Irishstevie approved these changes
Love Just tested Without an issue <3

2023-02-20 14:01 UTC, M4RFY commented
i like the idea

2023-02-20 14:02 UTC, M4RFY approved these changes
Perfectly Working

2023-02-20 16:09 UTC, Twikii approved these changes
Works well

2023-02-21 02:28 UTC, zwkf commented on html/js/app.js
> +        $("#item-amount").fadeOut(0);
`fadeOut()` with `0` duration seems a little odd. 
Maybe `hide()` would be better suited here?

http://api.jquery.com/hide/

2023-02-21 02:29 UTC, zwkf commented on html/js/app.js
> +    $("#item-amount").fadeIn(0);
Refer to above comment about hide/show

2023-02-21 02:30 UTC, zwkf commented on html/js/app.js
> +                    break
missing semi colon

2023-02-22 00:12 UTC, zwkf requested changes
Left some comments

2023-02-23 18:57 UTC, i-kulgu commented
> Left some comments

Fixed all of the comments and added a configurable option to hide player names upon giving item.

2023-03-08 03:13 UTC, zwkf commented
Note to self: test this

2023-05-09 13:27 UTC, closed without merging