Get rid of trolls opening inventories!
qbcore-framework/qb-inventory pull request #429
Opened 2023-03-18 07:17 UTC by Mane48

## Description

Hey, yes. Literally, it will try its best to get rid of the trolls that open the inventory. If they are modding and try the famous [QB] Open Inventory trigger it will yeet them from the server and ban them!

_Im just waiting on a modder to join my server and try it so I can see it work!_ 

It does work! I kinda see how it does up the amount of code that is required but ay... it'll def reduce the amount of trolls!

Update :

Upon more testing i've realized that some of staff may be banned, its not an always kind of deal but there is a possibility, I dont know what exactly could cause this but if anyone has any suggestions feel free to push them!

Update 2 :

Downside is that it doesnt actually work properly if they're close to you. It'll just run it like either a robbery or so.

## Checklist

- [x] I have personally loaded this code into an updated qbcore project and checked all of its functionality.
- [x] My code fits the style guidelines.
- [x] My PR fits the contribution guidelines.

2023-03-18 23:39 UTC, Sharkiiie requested changes
Follow linting and styling guidelines.
Please make sure the file is using 4 spaces per indent rather than tabs, and each new block of code is indented one time.

I would highly suggest using the Lua extension by sumneko and enabling the formatter.
It makes it much easier to follow the guidelines and does most of the work for you.

2023-03-18 23:39 UTC, Sharkiiie commented on server/main.lua
> +local function BanPlayer(src)
I would suggest using the ExploitBan export from core to avoid redundant code.

2023-03-18 23:39 UTC, Sharkiiie commented on server/main.lua
> +						DropPlayer(src, "Invisible or invincible? Which one 😂")
Player drop messages should be clear and concise, along the lines of "you have been kicked / banned for x"
I would suggest putting the drop message in the locales files as well.

2023-03-18 23:39 UTC, Sharkiiie commented on server/main.lua
> +						DropPlayer(src, "Invisible or invincible? Which one 😂")
Player drop messages should be clear and concise, along the lines of "you have been kicked / banned for x"
I would suggest putting the drop message in the locales files as well.

2023-03-19 01:04 UTC, Mane48 commented on server/main.lua
> +						DropPlayer(src, "Invisible or invincible? Which one 😂")
Alright sure thing, I appreciate it ill implement and fix all the things you mentioned!

2023-03-26 21:39 UTC, Sharkiiie commented
Still not following linting / styling guidelines for spaces rather than tabs.
I'll have to give everything else a closer review later.

2023-04-06 04:32 UTC, Mane48 commented
Hey I thought I actually did follow it. In my side they show up as spaces 4 spaces instead of tabs. How can I check this again?

2023-10-10 15:44 UTC, closed without merging