Fixed equiped weapon not removing from the player hand on clear inventory.
qbcore-framework/qb-inventory pull request #601
Opened 2024-11-24 22:00 UTC by adhershmnair

## Description
Equipped weapon doesn't remove from player's hand when inventory cleared.

## Checklist

- [x] I have personally loaded this code into an updated qbcore project and checked all of its functionality.
- [x] My code fits the style guidelines.
- [x] My PR fits the contribution guidelines.

2024-11-24 22:30 UTC, adhershmnair commented on server/functions.lua
> +        end
Remove all equipped weapon from ped on clear inventory.

2024-11-25 17:16 UTC, Qwerty1Verified requested changes

2024-11-25 17:16 UTC, Qwerty1Verified commented on server/functions.lua
> +        if weapon ~= GetHashKey('WEAPON_UNARMED') then
Good change. It'd be better to use backticks rather than calculate the hash each time with the native.
```suggestion
        if weapon ~= `WEAPON_UNARMED` then
```

2024-11-26 02:24 UTC, adhershmnair commented on server/functions.lua
> +        if weapon ~= GetHashKey('WEAPON_UNARMED') then
@Qwerty1Verified 
Updated to use backticks to avoid unnecessary runtime hash calculations and improve efficiency.
Thanks.

2024-11-26 03:00 UTC, Qwerty1Verified approved these changes

2024-11-26 03:47 UTC, merged