Refactor HTML: Remove unnecessary header tags, improve design, and fix layout bugs
qbcore-framework/qb-inventory pull request #604
Opened 2024-11-26 17:04 UTC by adhershmnair

## Description

403 Forbidden fontawesome script.
![image](https://github.com/user-attachments/assets/5f704b21-f8be-478f-ae5e-7335d88c55ce)

Amount overflow issue.
![image](https://github.com/user-attachments/assets/78286a5d-d442-41ed-9818-11f6de3a7449)

## Checklist

- [x] I have personally loaded this code into an updated qbcore project and checked all of its functionality.
- [x] My code fits the style guidelines.
- [x] My PR fits the contribution guidelines.

2024-11-26 18:39 UTC, adhershmnair commented on html/app.js
> +
If player drag items from player inventory to shop inventory, currently it was swapping the items in inventory, which was confusing.

Added warning when we do this.

2024-11-26 18:44 UTC, adhershmnair commented on html/app.js
> +                }
Add a warning for first-time users when they attempt to make a bulk purchase without specifying the amount. Some players forget to enter the amount, resulting in an unintended bulk purchase.

2024-11-26 18:47 UTC, adhershmnair commented on html/app.js
>              }
Fixed inventoryError function to show color in correct Inventory and fixed the slot id issue.

2024-11-26 18:49 UTC, adhershmnair commented on html/main.css
> +
Hide the input number spinner from input field.

2025-01-09 14:29 UTC, Qwerty1Verified commented on html/app.js
> +                }
This would just look like you're not allowed to buy an item at first, right?

2025-01-10 17:19 UTC, Qwerty1Verified commented
Warning:
![image](https://github.com/user-attachments/assets/f09e1cee-5d28-457d-baf2-2f9687b6c280)
Error:
![image](https://github.com/user-attachments/assets/0745745d-c36c-416e-90fc-655079f9b20b)

2025-01-10 17:29 UTC, Qwerty1Verified requested changes

2025-01-10 17:29 UTC, Qwerty1Verified commented on html/app.js
> +                slotElement.style.backgroundColor = warning ? "yellow" : "red";
I think this could be better by opting for a softer opacity, like `#ffff002e` for yellow, and `#ff00002e` for red.
Yellow:
![image](https://github.com/user-attachments/assets/3738db7f-f50b-44b4-a2bd-b24013020e81)
Red:
![image](https://github.com/user-attachments/assets/91b5b290-46dc-4f7a-8cf9-93f12a1795d4)

2025-01-10 17:29 UTC, Qwerty1Verified commented on html/app.js
> +                        console.error("Purchasing items in bulk. Next time there will be no warning...");
A user may benefit by being able to understand what this condition is, perhaps by notifying them.

Another option for functionality could be by just defaulting to only taking 1 when `transferAmount` is `null`

2025-05-04 15:44 UTC, closed without merging